name: sliceit
description: "A modern expense-splitting app with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1
  firebase_database: ^11.0.2
  firebase_dynamic_links: ^6.0.2
  intl: ^0.18.1
  cloud_functions: ^5.1.0

  # State management
  provider: ^6.0.6

  # Image and ML
  image_picker: ^1.0.7
  google_ml_kit: ^0.16.0

  # Sharing & Links
  share_plus: ^9.0.0
  app_links: ^6.4.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/SliceIt.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
